### PR TITLE
Add gooddollar whitelist

### LINKED ISSUE #10: [feat] Add GoodDollar whitelist

### PR DESCRIPTION
**Pull request by Shloyem**
- Added the whitelisted check via GD NameService (and Identity contracts)
- Added mocks that helped to test on testnets where GoodDollar is not implemented
- Added prettier for formatting

We should
- Add more UT, after building the right infra for that
- Add the script for manual Celo Mainnet test via Ganache-CLI
- For nameService on deploy script - either 1) add addresses (or mocks) to testnets 2) deploy on the script

### CODE REVIEW

**Review by julienbrg — COMMENTED** [review]
- I had a 'override' error: https://github.com/w3hc/gcfa-contracts/actions/runs/5279387812/jobs/9549992115#step:6:13, so I restructured a bit.
- Are we sure we need a `setNameService` function? Right now anyone can change the value of the `nameService` address, and that could make the deposit function unaccessible. @bertux Do we remove it or do we make it settable only by the DAO?

**Comment by Shloyem** [comment]
> * I had a 'override' error: https://github.com/w3hc/gcfa-contracts/actions/runs/5279387812/jobs/9549992115#step:6:13, so I restructured a bit.
> * Are we sure we need a `setNameService` function? Right now anyone can change the value of the `nameService` address, and that could make the deposit function unaccessible. @bertux Do we remove it or do we make it settable only by the DAO?

I was using different version of Node and OpenZeppeling contracts, now I'm aligned and see the override problem.
Thanks for fixing, although IMHO we should keep OpenZeppelin contracts unchanged - ERC20Wrapper, and best practice would be to inherit and override some functions. And also remove interfaces from it. @julienbrg @bertux what do you think?

**Comment by Shloyem** [comment]
> * Are we sure we need a `setNameService` function? Right now anyone can change the value of the `nameService` address, and that could make the deposit function unaccessible. @bertux Do we remove it or do we make it settable only by the DAO?

Yes right now it's a problem that anyone could change it. Waiting for the DAO/Governance part :)

> * @bertux Do we remove it or do we make it settable only by the DAO?

Joining the question. We would want an option to change address, but also it's not core gCFA logic so maybe can be removed to somewhere else.

**Comment by bertux** [comment]
we use eXOF on Celo instead.

**Comment by julienbrg** [comment]
> we use eXOF on Celo instead.

In other words you want to shut down the whole project, right? 

Is there any reason why we force ourselves to use eXOF instead of gCFA?

**Comment by bertux** [comment]
Because eXOF has:
- the technical support of Mento Labs as native stable on Celo.
- the local support of Dunia on the African ground to make it exchangeable with their local cash agents network.

**Pull request closed without merging**
